spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: 8073
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
